=== ubirch/cannabis-certificate-schema/schema/DHC.certificate.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://ubirch.com/cannabis-certificate-schema.json",
  "type": "object",
  "title": "Cannabis Certificate",
  "description": "Digital Cannabis Certificate",
  "$comment": "Schema version 0.9.0",
  "required": [
    "ver",
    "p",
    "di",
    "ci",
    "i"
  ],
  "properties": {
    "ver": {
      "title": "Schema version",
      "description": "Version of the schema, according to Semantic versioning (ISO, https://semver.org/ version 2.0.0 or newer)",
      "type": "string",
      "pattern": "^\\d+.\\d+.\\d+$",
      "examples": [
        "0.9.0"
      ]
    },
    "p": {
      "description": "Surname(s), forename(s) - in that order",
      "$ref": "DHC.core.schema.json#/$defs/person"
    },
    "di": {
      "description": "ISO8601 date: date when certificate was issued",
      "type": "string",
      "format": "date"
    },
    "ci": {
      "description": "Identifier for this certificate",
      "$ref": "DHC.core.schema.json#/$defs/certificate-id"
    },
    "i": {
      "description": "Cannabis Certificate Group",
      "type": "array",
      "items": {
        "$ref": "DHC.types.schema.json#/$defs/cannabis_patient_certificate"
      },
      "minItems": 1,
      "maxItems": 3
    }
  }
}

=== ubirch/cannabis-certificate-schema/examples/cannabis-certificate-01.json
{
  "p": {
    "fnt": "MUELLER<MUSTERFRAU",
    "gnt": "MAXIMILIANE<ISOLDE",
    "fn": "MÃ¼ller-Musterfrau",
    "gn": "Maximiliane Isolde",
    "dob": "1980-01-20"
  },
  "i": [
    {
      "pi": "ub:C123401/239855",
      "bi": "ub:GCSF314F",
      "a": 2.5,
      "u": "ml",
      "f": "e",
      "thc": 0.12,
      "cbd": 0.0822,
      "exp": "2025-12-10"
    }
  ],
  "di": "2022-02-03",
  "ci": "dhc:1:ub:DE/JBI32302/4Ef57666/22",
  "ver": "1.0.0"
}
